/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyectobancos.Vistas;

import proyectobancos.Administradores.AdministradorPrincipal;

/**
 *
 * @author RUBEN
 */
public class VentanaEscogerGraficos extends javax.swing.JFrame {

    /**
     * Creates new form VentanaEscogerGraficos
     */
    public VentanaEscogerGraficos() {
        
        initComponents();
        
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPieTipo = new javax.swing.JLabel();
        lblFondoLabelBarraTipo1 = new javax.swing.JLabel();
        lblFondoLabelBarraTipo = new javax.swing.JLabel();
        lblbarrasTipo = new javax.swing.JLabel();
        lblFondoLabelBarraTipo2 = new javax.swing.JLabel();
        lblFondoLabelBarraTipo3 = new javax.swing.JLabel();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPieTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblPieTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblPieTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPieTipo.setText("Pie por tipo cliente");
        lblPieTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPieTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblPieTipoMouseReleased(evt);
            }
        });
        getContentPane().add(lblPieTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 57, 200, 42));

        lblFondoLabelBarraTipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobancos/Imagenes/tipoBusqueda.fw.png"))); // NOI18N
        getContentPane().add(lblFondoLabelBarraTipo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, -1, -1));

        lblFondoLabelBarraTipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobancos/Imagenes/tipoBusqueda.fw.png"))); // NOI18N
        getContentPane().add(lblFondoLabelBarraTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, -1));

        lblbarrasTipo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblbarrasTipo.setForeground(new java.awt.Color(255, 255, 255));
        lblbarrasTipo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblbarrasTipo.setText("Barras por tipo cliente");
        lblbarrasTipo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblbarrasTipo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lblbarrasTipoMouseReleased(evt);
            }
        });
        getContentPane().add(lblbarrasTipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 200, 42));

        lblFondoLabelBarraTipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobancos/Imagenes/tipoBusqueda.fw.png"))); // NOI18N
        getContentPane().add(lblFondoLabelBarraTipo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        lblFondoLabelBarraTipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobancos/Imagenes/tipoBusqueda.fw.png"))); // NOI18N
        getContentPane().add(lblFondoLabelBarraTipo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, -1, -1));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectobancos/Imagenes/bgPrincipal.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 360));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblPieTipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPieTipoMouseReleased

        AdministradorPrincipal.getInstance().mostrarGraficosPieTipoCliente();
        
        
    }//GEN-LAST:event_lblPieTipoMouseReleased

    private void lblbarrasTipoMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblbarrasTipoMouseReleased
        // TODO add your handling code here:
        AdministradorPrincipal.getInstance().mostrarGraficosBarrasTipoCliente();
    }//GEN-LAST:event_lblbarrasTipoMouseReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEscogerGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEscogerGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEscogerGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEscogerGraficos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEscogerGraficos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel lblFondoLabelBarraTipo;
    private javax.swing.JLabel lblFondoLabelBarraTipo1;
    private javax.swing.JLabel lblFondoLabelBarraTipo2;
    private javax.swing.JLabel lblFondoLabelBarraTipo3;
    private javax.swing.JLabel lblPieTipo;
    private javax.swing.JLabel lblbarrasTipo;
    // End of variables declaration//GEN-END:variables
}
